"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
const shots=Array.from({length:24},(_,i)=>{const station=Math.floor(i/4)+1,shot=i%4+1;return {station,shot,foot:station===6?"either":shot<=2?"left":"right",value:station===6?2:1}});
export default function App(){
 const [players,setPlayers]=useState([]),[player,setPlayer]=useState(null),[screen,setScreen]=useState("pick"),[i,setI]=useState(0),[results,setResults]=useState([]),[history,setHistory]=useState([]),[leaders,setLeaders]=useState([]);
 useEffect(()=>{supabase.from("players").select("*").eq("active",true).order("name").then(({data})=>setPlayers(data||[]));},[]);
 const current=shots[i],score=useMemo(()=>results.reduce((a,x)=>a+(x.scored?x.value:0),0),[results]);
 async function record(scored){const next=[...results,{...current,scored}];setResults(next);if(i<23){setI(i+1);return;} const total=next.reduce((a,x)=>a+(x.scored?x.value:0),0);const left=next.filter(x=>x.foot==="left"&&x.scored).length,right=next.filter(x=>x.foot==="right"&&x.scored).length,long=next.filter(x=>x.station===6&&x.scored).length;
 const {data:c,error}=await supabase.from("challenges").insert({player_id:player.id,total_score:total,successful_shots:next.filter(x=>x.scored).length,left_scores:left,right_scores:right,long_range_scores:long,xp_earned:25}).select().single();
 if(!error){await supabase.from("shots").insert(next.map(x=>({challenge_id:c.id,station:x.station,shot_number:x.shot,foot:x.foot,scored:x.scored,points:x.scored?x.value:0})));await supabase.from("players").update({xp:(player.xp||0)+25}).eq("id",player.id);}
 setScreen("result");
 }
 async function loadDash(p){setPlayer(p);const [{data:h},{data:l}]=await Promise.all([supabase.from("challenges").select("*").eq("player_id",p.id).order("completed_at",{ascending:false}).limit(10),supabase.from("weekly_leaderboard").select("*")]);setHistory(h||[]);setLeaders(l||[]);setScreen("home");}
 function start(){setI(0);setResults([]);setScreen("challenge")}
 if(screen==="pick")return <main><header><b>GAELIC 24</b><span>Solo Shooting Challenge</span></header><section><h1>Who’s training?</h1><p>Select your player profile to begin.</p><div className="players">{players.map(p=><button key={p.id} onClick={()=>loadDash(p)}>{p.name}<small>{p.xp||0} XP</small></button>)}</div></section></main>;
 if(screen==="challenge")return <main><header><b>GAELIC 24</b><span>{score}/28</span></header><section><div className="progress">Shot {i+1} of 24 · Station {current.station}</div><img className="pitch" src="/pitch-map.png" alt="Official Gaelic 24 shooting positions"/><h1>Station {current.station}</h1><div className="instruction">{current.station===6?"EITHER FOOT · 2 POINTS":current.foot.toUpperCase()+" FOOT · 1 POINT"}</div><p>Shot {current.shot} of 4</p><div className="actions"><button className="miss" onClick={()=>record(false)}>MISS</button><button className="score" onClick={()=>record(true)}>SCORE</button></div>{results.length>0&&<button className="link" onClick={()=>{setResults(results.slice(0,-1));setI(Math.max(0,i-1))}}>Undo last shot</button>}</section></main>;
 if(screen==="result"){const left=results.filter(x=>x.foot==="left"&&x.scored).length,right=results.filter(x=>x.foot==="right"&&x.scored).length,long=results.filter(x=>x.station===6&&x.scored).length;return <main><header><b>GAELIC 24</b></header><section><div className="trophy">Challenge complete</div><h1 className="big">{score}<small>/28</small></h1><div className="stats"><div><b>{left}/10</b><span>Left</span></div><div><b>{right}/10</b><span>Right</span></div><div><b>{long}/4</b><span>40m+</span></div></div><button className="primary" onClick={()=>loadDash(player)}>Done</button></section></main>}
 const pb=Math.max(0,...history.map(x=>x.total_score));return <main><header><b>GAELIC 24</b><button className="link" onClick={()=>setScreen("pick")}>Switch player</button></header><section><p>Welcome back</p><h1>{player.name}</h1><div className="hero"><span>Personal best</span><b>{pb}<small>/28</small></b><span>{player.xp||0} XP</span></div><button className="primary" onClick={start}>Start 24-shot challenge</button><h2>Weekly leaderboard</h2>{leaders.slice(0,5).map((x,n)=><div className="row" key={x.player_id}><span>{n+1}. {x.name}</span><b>{x.best_score}/28</b></div>)}<h2>Recent challenges</h2>{history.length?history.map(x=><div className="row" key={x.id}><span>{new Date(x.completed_at).toLocaleDateString()}</span><b>{x.total_score}/28</b></div>):<p>No challenges yet. Set the first score.</p>}</section></main>
}